---
title: "R Notebook"
output: html_notebook
---

```{r}
pacman::p_load(tidyverse, corrr, ggplot2, lmerTest, ggeffects, sjPlot, tidyverse, heatmaply, pheatmap, gplots, RColorBrewer)
```

```{r}
indDiffDf <- read.csv("./output/PFindDiffDf.csv")
indDiffDf[c("Rep","Info", "partyN")] <- NULL
#longDf <- read.csv("./output/PFfullDf.csv")
longDf <- read.csv("./output/PFfullDfzip.csv")
indDiffDf <- merge(indDiffDf, longDf[match(unique(longDf$subID), longDf$subID),][c("subID","Polit")], by = "subID")
indDiffDf$polStrength <- abs(7- indDiffDf$Polit )
issExpDf <- read.csv("./output/issueAgDf.csv")
longDf$partyN <- as.factor(longDf$partyN)
longDf$Rep <- as.factor(longDf$Rep)
contrasts(longDf$Rep) <- contr.sum(3)
longDf$RepN <- as.factor(longDf$RepN)
longDf$RepN <- relevel(longDf$RepN,"In")
longDf$Info <- as.factor(longDf$Info)
contrasts(longDf$Info) <- contr.sum(2)
longDf$partyN <- as.factor(longDf$partyN)
contrasts(longDf$partyN) <- contr.sum(2)
longDf <- longDf[order(longDf$subID, longDf$issues),]
demDf <- subset(longDf, partyN == "Dem")
repDf <- subset(longDf, partyN == "Rep")
shortDf1 <- longDf[!duplicated(longDf$subID),]
```

```{r, include=FALSE}
indDiffDf2 <- read.csv("./output/PFindDiffDf2.csv")
longDf2 <- read.csv("./output/PFfullDf2.csv")
issExpDf2 <- read.csv("./output/issueAgDf2.csv")
longDf2$partyN <- as.factor(longDf2$partyN)
longDf2$Rep <- as.factor(longDf2$Rep)
longDf2$Rep <- factor(longDf2$Rep, c("Non","Rep","Dem"))
longDf2$Rep <- relevel(longDf2$Rep,"Non")
contrasts(longDf2$Rep) <- contr.sum(3)
longDf2$RepN <- as.factor(longDf2$RepN)
longDf2$RepN <- relevel(longDf2$RepN,"In")
longDf2$Info <- as.factor(longDf2$Info)
contrasts(longDf2$Info) <- contr.sum(2)
longDf2$partyN <- as.factor(longDf2$partyN)
contrasts(longDf2$partyN) <- contr.sum(2)
demDf <- subset(longDf2, partyN == "Dem")
repDf <- subset(longDf2, partyN == "Rep")
longDf2 <- longDf2[order(longDf2$subID, longDf2$issues),]
longDf2$polStrength <- abs(longDf2$Polit - 4)
shortDf2 <- longDf2[!duplicated(longDf2$subID),]
indDiffDf2 <- merge(indDiffDf2, shortDf2[c("subID","Polit")], by = "subID")
```

```{r}
longDfc<- longDf[c("subID","issues","eval")]
longDfc <- longDfc[order(longDfc$subID, longDfc$issues),]
wideDf <- longDfc %>% pivot_wider(names_from = issues, values_from = eval)

corMat <- wideDf %>% select(`1`:`100`) %>% cor(.,use="pairwise.complete.obs")
corMatZ <- psych::fisherz(corMat)
corVector <- corMatZ[lower.tri(corMatZ)]
```

```{r}
colnames(corMat) <- longDf$label[match(unique(longDf$issues), longDf$issues) ]
rownames(corMat) <- longDf$label[match(unique(longDf$issues), longDf$issues) ]
jpeg("~/Desktop/test.png", height=10, width=15, units="in",res=300)
heatmap(corMat, Colv = "Rowv", symm=TRUE, cexRow=.5, cexCol=.5)
dev.off()
```

```{r}
outphm<-pheatmap(corMat, fontsize_row = 6, fontsize_col = 6, angle_col = 45, angle_row =45, width=100, height = 200 )
outphm
```

```{r}
out<-heatmaply::ggheatmap(corMat, grid_gap=2, colorbar_len=50, grid_size = 5 , Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 8.5, fontsize_col = 8.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100))
```

```{r}
library(RColorBrewer)
out<-heatmaply::ggheatmap(corMat, colorbar_len=50, grid_size = 5 , Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 8.5, fontsize_col = 8.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100))
```




```{r}
heatmaply_cor(round(corMat,3), Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 2.5, fontsize_col = 2.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name =
  "RdYlBu")))(100) )
```


```{r}
mds2<-corMat %>%
  psych::cor2dist(.) %>%
  MASS::isoMDS(k=2) %>%
  .$points %>%
  as_tibble()
colnames(mds2) <- c("Dim.1", "Dim.2")
library(ggpubr)
ggscatter(mds2, x = "Dim.1", y = "Dim.2", 
          label = longDf$label[match(unique(longDf$issues), longDf$issues) ],
          font.label = c(5, "bold", "black"),
          size = 1,
          repel = TRUE)
```


```{r}
allDists <- tapply(longDf$eval, longDf$subID, dist)

issuesFrame <- longDf[match(unique(longDf$issues), 1:100),]

allDistsOut <- tapply(longDf$bootEvalOut, longDf$subID, dist)

allDistsIn <- tapply(longDf$bootEvalIn, longDf$subID, dist)

demIssues <- demDf[match(unique(demDf$issues), 1:100),]
repIssues <- repDf[match(unique(repDf$issues), 1:100),]

demDistM<-as.matrix(dist(c(demIssues$bootEvalIn, demIssues$bootEvalOut)))
demDistM<-as.matrix(demDistM[-(1:100),-(101:200)])
demDistV <- demDistM[lower.tri(demDistM)]

repDistM<-as.matrix(dist(c(repIssues$bootEvalIn, repIssues$bootEvalOut)))
repDistM<-as.matrix(repDistM[-(1:100),-(101:200)])
repDistV <- repDistM[lower.tri(repDistM)]

reputDist <- dist(issuesFrame$reput)
reputMatrix <- as.matrix(reputDist)
reputVector <- reputMatrix[lower.tri(reputMatrix)]

reputDDist <- dist(issuesFrame$reputD)
reputDMatrix <- as.matrix(reputDDist)
reputDVector <- reputDMatrix[lower.tri(reputDMatrix)]

honestDist <- dist(issuesFrame$honest)
honestMatrix <- as.matrix(honestDist)
honestVector <- honestMatrix[lower.tri(honestMatrix)]

changeDist <- dist(issuesFrame$change)
changeMatrix <- as.matrix(changeDist)
changeVector <- changeMatrix[lower.tri(changeMatrix)]

politicDist <- dist(issuesFrame$politic)
politicMatrix <- as.matrix(politicDist)
politicVector <- politicMatrix[lower.tri(politicMatrix)]

breadthDist <- dist(issuesFrame$breadth)
breadthMatrix <- as.matrix(breadthDist)
breadthVector <- breadthMatrix[lower.tri(breadthMatrix)]

fullMat <- as.data.frame(matrix(ncol=16))
uIds<-unique(longDf$subID)
for(i in 1:length(uIds)){
  j <- uIds[i]
  
  distMatrix <- as.matrix(allDists[[i]])
  distVector <- distMatrix[lower.tri(distMatrix)]
  
  distMatrixOut <- as.matrix(allDistsOut[[i]])
  distVectorOut <- distMatrixOut[lower.tri(distMatrixOut)]
  
  distMatrixIn <- as.matrix(allDistsIn[[i]])
  distVectorIn <- distMatrixOut[lower.tri(distMatrixIn)]
  
  if( as.character(unique(longDf$partyN[longDf$subID==j]))=="Rep" ){
    partyDistV <- repDistV
  }else if( as.character(unique(longDf$partyN[longDf$subID==j]))=="Dem" ){
    partyDistV <- demDistV
  }
  
  subMat <- cbind(data.frame(subID=j,dist=distVector,RepN=unique(longDf$RepN[longDf$subID==j]), partyN=unique(longDf$partyN[longDf$subID==j]), Info=unique(longDf$Info[longDf$subID==j]), Rep=unique(longDf$Rep[longDf$subID==j]), reputD = reputVector, reputDD = reputDVector, changeD = changeVector, honestD = honestVector, politicD = politicVector, breadthD = breadthVector, distOut = distVectorOut, distIn = distVectorIn, distParty  = partyDistV, corr = corVector ))
  names(fullMat) <- colnames(subMat)
  fullMat <- rbind(fullMat, subMat)
}

#x <- c("subID","dist")
#fullDistDf <- as.data.frame(fullMat)
#names(fullDistDf) <- x
fullDistDf <- as.data.frame(fullMat)
fullDistDf<-fullDistDf[!is.na(fullDistDf$subID),]

fullDistDf$distSTrans <- 1/(1+fullDistDf$dist)
fullDistDf$distETrans <- 1/(exp(fullDistDf$dist))

#fullDistDf <- merge(fullDistDf, longDf[c("subID","RepN","partyN","Info")], by = "subID")

fullDistDf <- merge(fullDistDf, indDiffDf, by = "subID")

colnames(fullDistDf)

fullDistDf <- fullDistDf %>% select(subID, dist, RepN, partyN, Info, Rep, corr, distSTrans, distETrans, affPol:falsify, Polit, polStrength)

write.csv(fullDistDf, "~/Google Drive/Volumes/Research Project/Preference Falsification/Analysis/output/distanceDf.csv")

arrow::write_parquet(fullDistDf, "~/Google Drive/Volumes/Research Project/Preference Falsification/Analysis/output/distanceDf.parquet")
```

```{r}
longDf2c<- longDf2[c("subID","issues","eval")]
longDf2c <- longDf2c[order(longDf2c$subID, longDf2c$issues),]
wideDf <- longDf2c %>% pivot_wider(names_from = issues, values_from = eval)

corMat <- wideDf %>% select(`1`:`100`) %>% cor(.,use="pairwise.complete.obs")
corMatZ <- psych::fisherz(corMat)
corVector <- corMatZ[lower.tri(corMatZ)]
```

```{r}
colnames(corMat) <- longDf2$label.x[match(unique(longDf2$issues), longDf2$issues) ]
rownames(corMat) <- longDf2$label.x[match(unique(longDf2$issues), longDf2$issues) ]
jpeg("~/Desktop/test.png", height=10, width=15, units="in",res=300)
heatmap(corMat, Colv = "Rowv", symm=TRUE, cexRow=.5, cexCol=.5)
dev.off()
```

```{r}
outphm<-pheatmap(corMat, fontsize_row = 6, fontsize_col = 6, angle_col = 45, angle_row =45, width=100, height = 200 )

```

```{r}
out<-heatmaply::ggheatmap(corMat, grid_gap=2, colorbar_len=50, grid_size = 5 , Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 8.5, fontsize_col = 8.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100))

```

```{r}
out<-heatmaply::ggheatmap(corMat, colorbar_len=50, grid_size = 5 , Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 8.5, fontsize_col = 8.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100))

```




```{r}
heatmaply_cor(round(corMat,3), Rowv=outphm[[1]], Colv=outphm[[2]], revC=TRUE, fontsize_row = 2.5, fontsize_col = 2.5, angle_col = 45, angle_row =45,  limits = c(-1, 1), colors = colorRampPalette(rev(brewer.pal(n = 7, name =
  "RdYlBu")))(100) )
```


```{r}
mds2<-corMat %>%
  psych::cor2dist(.) %>%
  MASS::isoMDS(k=2) %>%
  .$points %>%
  as_tibble()
colnames(mds2) <- c("Dim.1", "Dim.2")
library(ggpubr)
ggscatter(mds2, x = "Dim.1", y = "Dim.2", 
          label = longDf2$label.x[match(unique(longDf2$issues), longDf2$issues) ],
          font.label = c(5, "bold", "black"),
          size = 1,
          repel = TRUE)
```


```{r}
allDists <- tapply(longDf2$eval, longDf2$subID, dist)

issuesFrame <- longDf2[match(unique(longDf2$issues), 1:100),]

allDistsOut <- tapply(longDf2$bootEvalOut, longDf2$subID, dist)

allDistsIn <- tapply(longDf2$bootEvalIn, longDf2$subID, dist)

demIssues <- demDf[match(unique(demDf$issues), 1:100),]
repIssues <- repDf[match(unique(repDf$issues), 1:100),]

demDistM<-as.matrix(dist(c(demIssues$bootEvalIn, demIssues$bootEvalOut)))
demDistM<-as.matrix(demDistM[-(1:100),-(101:200)])
demDistV <- demDistM[lower.tri(demDistM)]

repDistM<-as.matrix(dist(c(repIssues$bootEvalIn, repIssues$bootEvalOut)))
repDistM<-as.matrix(repDistM[-(1:100),-(101:200)])
repDistV <- repDistM[lower.tri(repDistM)]

reputDist <- dist(issuesFrame$reput)
reputMatrix <- as.matrix(reputDist)
reputVector <- reputMatrix[lower.tri(reputMatrix)]

reputDDist <- dist(issuesFrame$reputD)
reputDMatrix <- as.matrix(reputDDist)
reputDVector <- reputDMatrix[lower.tri(reputDMatrix)]

honestDist <- dist(issuesFrame$honest)
honestMatrix <- as.matrix(honestDist)
honestVector <- honestMatrix[lower.tri(honestMatrix)]

changeDist <- dist(issuesFrame$change)
changeMatrix <- as.matrix(changeDist)
changeVector <- changeMatrix[lower.tri(changeMatrix)]

politicDist <- dist(issuesFrame$politic)
politicMatrix <- as.matrix(politicDist)
politicVector <- politicMatrix[lower.tri(politicMatrix)]

breadthDist <- dist(issuesFrame$breadth)
breadthMatrix <- as.matrix(breadthDist)
breadthVector <- breadthMatrix[lower.tri(breadthMatrix)]

#dist1 <- lower.tri(as.matrix(allDists[[1]]))
#dist1 <- as.matrix(allDists[[1]])
#dist2 <- dist1[lower.tri(dist1)]

#fullMat <- matrix(ncol=2)
fullMat2 <- as.data.frame(matrix(ncol=16))
uIds<-unique(longDf2$subID)
for(i in 1:length(uIds)){
  j <- uIds[i]
  
  distMatrix <- as.matrix(allDists[[i]])
  distVector <- distMatrix[lower.tri(distMatrix)]
  
  distMatrixOut <- as.matrix(allDistsOut[[i]])
  distVectorOut <- distMatrixOut[lower.tri(distMatrixOut)]
  
  distMatrixIn <- as.matrix(allDistsIn[[i]])
  distVectorIn <- distMatrixOut[lower.tri(distMatrixIn)]
  
  if( as.character(unique(longDf2$partyN[longDf2$subID==j]))=="Rep" ){
    partyDistV <- repDistV
  }else if( as.character(unique(longDf2$partyN[longDf2$subID==j]))=="Dem" ){
    partyDistV <- demDistV
  }
  
  subMat <- cbind(data.frame(subID=j,dist=distVector,RepN=unique(longDf2$RepN[longDf2$subID==j]), partyN=unique(longDf2$partyN[longDf2$subID==j]), Info=unique(longDf2$Info[longDf2$subID==j]), Rep=unique(longDf2$Rep[longDf2$subID==j]), reputD = reputVector, reputDD = reputDVector, changeD = changeVector, honestD = honestVector, politicD = politicVector, breadthD = breadthVector, distOut = distVectorOut, distIn = distVectorIn, distParty  = partyDistV, corr = corVector ))
  names(fullMat2) <- colnames(subMat)
  fullMat2 <- rbind(fullMat2, subMat)
}

#x <- c("subID","dist")
#fullDistDf <- as.data.frame(fullMat)
#names(fullDistDf) <- x
fullDistDf2 <- as.data.frame(fullMat2)
fullDistDf2 <- fullDistDf2[!is.na(fullDistDf2$subID),]

fullDistDf2$distSTrans <- 1/(1+fullDistDf2$dist)
fullDistDf2$distETrans <- 1/(exp(fullDistDf2$dist))

indDiffDf2 <- indDiffDf2 %>% select(subID, Polit.x:falsify)
fullDistDf2 <- merge(fullDistDf2, indDiffDf2, by = "subID")

fullDistDf2$polStrength <- abs(4-fullDistDf2$Polit.x)

fullDistDf2 <- fullDistDf2 %>% select(subID, dist, RepN, partyN, Info, Rep, corr, distSTrans, distETrans, affPol:falsify, Polit.x, polStrength)
```